// vue/1.todos/vue-todos/src/components/quote.vue
<template>
<div class="panel panel-default">
<div class="panel-body">
{{qt.content}}
</div>
<div class="panel-footer">
            <div v-if="editing">
            <input type="text" v-model="EditValue" id="">
            <a @click="onUpdate"> save</a>
            <a @click="onCancel"> cancel</a>
            
            </div>
            <div v-if="!editing">
            <a @click="onEdit"> Edit</a>
            <a @click="onDelete"> Delete</a>
            </div>
</div>
</div>
</template>
<script>
import axios from 'axios'
    export default{
        props:['qt'],
        data(){
            return {
                editing:false,
                EditValue:this.qt.content
            }
        },
        methods:{
            onEdit(){
                this.editing=true;
            },
            onCancel(){
                this.editing=false;
            },
            onDelete(){
                
                axios.delete('http://localhost/laravel/laraveltodo/todo/public/api/quote/'+this.qt.id+this.$auth.getTokenBody())
                .then((response)=>this.$emit('quoteDeleted',this.qt.id))
                .catch((error)=>console.log(error));
            },
            onUpdate(){
                axios.put('http://localhost/laravel/laraveltodo/todo/public/api/quote/'+this.qt.id+this.$auth.getTokenBody(),{content:this.EditValue})
                .then((response)=>this.qt.content=response.data.quote.content)
                .catch((error)=>console.log(error));

            }
           
        }
    }
</script>

// angular/4.todos/todos/src/app/quote/quote.component.ts
import { QuoteService } from '../app.quote.service';
import { Quote } from '../quote.interface';
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-quote',
  templateUrl: './quote.component.html',
  styleUrls: ['./quote.component.css']
})
export class QuoteComponent implements OnInit {
  @Input() quote:Quote;
  @Output() DeleteQuote=new EventEmitter<any>();
  editValue:string;
  editing:boolean=false;
  constructor(private quoteService:QuoteService) { }

  ngOnInit() {
  }
  onEdit(){
this.editing=true;
this.editValue=this.quote.content;

  }
  onCancel()
{

this.editing=false;
  
}
onUpdate(){
this.editing=false;
this.quoteService.updateQuote(this.quote.id,this.editValue)
.subscribe((quote)=>this.quote=quote.quote)
}
onDelete(){
this.quoteService.deleteQuote(this.quote.id)
.subscribe(()=>this.DeleteQuote.emit(this.quote));

}



}

<div class="panel panel-default">
  <div class="panel-body">
    {{quote.content}}
  </div>
  <div class="panel-footer">
    <div class="" *ngIf="editing">
      <input type="text" [(ngModel)]="editValue" name="" id="">
    <a (click)="onUpdate()">Save</a>
    <a (click)="onCancel()">Cancel</a>
    </div>
    
    <div class=""*ngIf="!editing" >
    <a  (click)="onEdit()">Edit</a>
    <a  (click)="onDelete()">Delete</a>
    <a  (click)="onCancel()">Cancel</a>
    </div>

  </div>
  
</div>
