// angular/4.todos/todos/src/app/quotes/quotes.component.ts
import { Quote } from '../quote.interface';
import { Component, OnInit } from '@angular/core';
import {Response} from '@angular/http';
import { QuoteService } from "app/app.quote.service";
@Component({
  selector: 'app-quotes',
  templateUrl: './quotes.component.html',
  styleUrls: ['./quotes.component.css']
})
export class QuotesComponent implements OnInit {
quotes:Quote[];

  constructor(private quotesService:QuoteService) { }

  ngOnInit() {
  }
  onGetQuotes(){
  this.quotesService.getQuotes()
  .subscribe(
    (quotes:Quote[])=>{console.log(quotes);this.quotes=quotes;},
    (error:Response)=>console.log(error)
    );
  }
deleteQuote(quote){
  const position=this.quotes.findIndex(
    (quoteEl:Quote)=> {return quoteEl.id==quote.id}
    );
    this.quotes.splice(position,1);

}

}

<button class="btn btn-primary" (click)="onGetQuotes()">GetQuotes</button>
<app-quote *ngFor="let quote of quotes" (DeleteQuote)="deleteQuote($event)" [quote]="quote" ></app-quote>

// vue/1.todos/vue-todos/src/components/quotes.vue
<template>
<div class=""> 
<button class="btn btn-primary" @click="onGetQuotes">拿取</button>
    <app-quote v-for="quote in quotes" :qt="quote" @quoteDeleted="onQuoteDeleted($event)"></app-quote>
</div>
</template>
<script>
import Quote from './quote.vue'
import axios from 'axios'
    export default{
        data(){
            return {
                quotes:[]
            }
        },
        components:{
            'app-quote':Quote
        },
        methods:{
            onGetQuotes(){
                axios.get('http://localhost/laravel/laraveltodo/todo/public/api/quotes')
                .then((response)=>this.quotes=response.data.quotes)
                .catch((error)=>console.log(error));
            },
            onQuoteDeleted(id){
               const position =this.quotes.findIndex((element)=> element.id==id);
               this.quotes.splice(position,1);
            }
        }
    }
</script>
